---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: h2dbdeploymnet
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: h2-db
  template:
    metadata:
      name: h2dbpod
      labels:
        app: h2-db
    spec:
      name: h2dbcontainer
      image: javeedit/h2-db
      ports:  
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: h2dbsvc
spec:
  type: NodePort
  selector:  
    app: h2-db
  ports:  
    - prot: 80
      targetPort: 8080
      nodePort: 30001
...